version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - streamlit_app

  streamlit_app:
    image: streamlit/streamlit:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: streamlit run app.py
    expose:
      - "8501"
